# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MP3s36W6ZZ-yXoX5tHN2xM32c2GR0eyZ
"""

print("hello world")

a = float(input("Enter the value: "))
b = float(input("Enter the value: "))
print(a**b)

a = 5
b = 6
print(a*b)

a = 5
b = 7
c = b, a
print(c)

pi = 3.14
r = float(input("Enter the the number: "))
area = pi*r*r
print(area)

a = 8
b = 5
print(a % b)

num = float(input("Enter the value: "))
if(num % 2 == 0):
  print("even")
else:
  print("odd")

num = float(input("Enter the value: "))
if(num == 0):
  print("Value is Zero")
elif(num > 0):
  print("Value is positive")
else:
  print("value is negetive")

age = 17
if(age >= 18):
  print("Eligible for voting")
else:
  print("not Eligible for voting")

d = {"a": 1, "b": 2}
d.update({"c": 3})
print(d)

d = {"a": 1, "b": 2}
print(list(d.keys()))

d = {"a": 100, "b": 200}
for k, v in d.items():
  print(k, v)

d = {"a": 1, "b": 2}
print(d.pop("b"))
print(d)

for i in range(1, 6):
    if i % 2 == 0:
        continue
    print(i)

for i in range(3):
  for j in range(3):
    print(i, j)

for i in range(3):
  pass
print("Done")

x = [1, 2, 3]
for i in x:
  x.remove(i)
print(x)

try:
  print("Hello")
finally:
  print("Finally block executed")

try:
  print(1/0)
except:
  print("Zero Division Error")
else:
  print("Else block executed")
finally:
  print("Finally block executed")